---
- hosts: all
  become: true
  become_user: root
  tasks:
  -name: update apt repo and cache on all
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
  
  -name: upgrade all packages on servers
  apt: upgrade=dist force_apt_get=yes
  
  - name: Install packages
    ansible.builtin.apt:
     name: "curl"
     state: "present"
     update_cache: true
     
  - name: install docker
    ansible.builtin.apt:
        name: "docker"
        state:  "present"
        update_cache: "true"
        
  - name: install firewalld
    ansible.builtin.apt:
        name: "firewalld"
        state: "present"
        update_cache: true
        
  - name: firewall 80/tcp
    ansible.posix.firewalld:
        zone: public
        port: 80/tcp
        permanent: yes
        state: enabled
        
  - name: firewall 8080/tcp
        zone: public
        port: 8080/tcp
        permanent: yes
        state: enabled
        
  - name: firewall 1834/tcp
        zone: public
        port: 1834/tcp
        permanent: yes
        state: enabled
        
  - name: restart firewalld
    ansible.builtin.service:
        name: firewalld
        state: restarted